/* Phase 4 — Exercise 3: Runtime shim for MLIR-compiled matmul.
 *
 * Calls the MLIR-compiled forward() function via the _mlir_ciface_ C wrapper.
 * The wrapper is generated by --llvm-request-c-wrappers in the lowering chain.
 *
 * Build and run via: bash scripts/phase4/ex4_compile_and_run.sh
 *
 * MemRef2D layout (matches mlir/include/mlir/ExecutionEngine/CRunnerUtils.h):
 *
 *   typedef struct {
 *       float *allocated;   // original allocation pointer (for dealloc)
 *       float *aligned;     // pointer to first element (what you index into)
 *       int64_t offset;     // offset from aligned to [0,0] (0 for simple cases)
 *       int64_t sizes[2];   // logical shape: {rows, cols}
 *       int64_t strides[2]; // strides in elements: {cols, 1} for row-major
 *   } MemRef2D;
 *
 * The C interface passes MemRef2D structs BY POINTER (not by value).
 * For a function returning a memref, the result descriptor is passed as the
 * first out-parameter (pointer), followed by the input descriptors.
 *
 * Signature for matmul(a, b) -> result:
 *   void _mlir_ciface_forward(MemRef2D *result, MemRef2D *a, MemRef2D *b);
 */

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* 2D memref descriptor for float32 */
typedef struct {
    float *allocated;
    float *aligned;
    int64_t offset;
    int64_t sizes[2];
    int64_t strides[2];
} MemRef2D;

/* Declaration of the MLIR-compiled function (C interface wrapper).
 * The exact name comes from --llvm-request-c-wrappers applied to @forward. */
void _mlir_ciface_forward(MemRef2D *result, MemRef2D *a, MemRef2D *b);

/* PyTorch reference: matmul(ones(4,4), ones(4,4)) = 4.0 everywhere */
#define ROWS 4
#define COLS 4
#define EXPECTED 4.0f
#define TOLERANCE 1e-5f

static void print_matrix(const char *name, float *data, int rows, int cols) {
    printf("%s:\n", name);
    for (int i = 0; i < rows; i++) {
        printf("  ");
        for (int j = 0; j < cols; j++)
            printf("%6.2f ", data[i * cols + j]);
        printf("\n");
    }
}

int main(void) {
    /* Input data: two 4x4 all-ones matrices */
    float a_data[ROWS * COLS], b_data[ROWS * COLS], out_data[ROWS * COLS];
    memset(out_data, 0, sizeof(out_data));
    for (int i = 0; i < ROWS * COLS; i++) {
        a_data[i] = 1.0f;
        b_data[i] = 1.0f;
    }

    /* MemRef2D descriptors — row-major, no offset */
    MemRef2D a      = { a_data,   a_data,   0, {ROWS, COLS}, {COLS, 1} };
    MemRef2D b      = { b_data,   b_data,   0, {ROWS, COLS}, {COLS, 1} };
    MemRef2D result = { out_data, out_data, 0, {ROWS, COLS}, {COLS, 1} };

    /* Call the MLIR-compiled matmul */
    _mlir_ciface_forward(&result, &a, &b);

    /* Print output */
    print_matrix("result = matmul(ones(4,4), ones(4,4))", result.aligned, ROWS, COLS);

    /* Verify against PyTorch reference (all elements should be 4.0) */
    int ok = 1;
    for (int i = 0; i < ROWS * COLS; i++) {
        if (fabsf(result.aligned[i] - EXPECTED) > TOLERANCE) {
            printf("MISMATCH at [%d]: got %.6f, expected %.6f\n",
                   i, result.aligned[i], EXPECTED);
            ok = 0;
        }
    }

    if (ok) {
        printf("\nAC4 PASS: output matches torch.matmul(ones(4,4), ones(4,4)) to 1e-5\n");
        return 0;
    } else {
        printf("\nAC4 FAIL: output does not match reference\n");
        return 1;
    }
}
